CREATE TABLE `kennisbank_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`itemType` enum('adviseur','beleidsdocument','toetsingskader') NOT NULL,
	`laag` enum('rijks','provinciaal','regionaal','gemeentelijk') NOT NULL,
	`scopeProvincie` varchar(50),
	`scopeRegioCode` varchar(50),
	`scopeGemeenteId` int,
	`naam` varchar(255) NOT NULL,
	`samenvatting` text,
	`toepassingscriteria` text,
	`triggers` json,
	`adviseurType` enum('intern','extern'),
	`adviseurCategorie` varchar(100),
	`adviseurTermijnWeken` int,
	`adviseurGrondslag` text,
	`adviseurIsVerplicht` boolean DEFAULT false,
	`adviseurContactEmail` varchar(320),
	`documentType` varchar(100),
	`documentUrl` text,
	`documentZoekterm` varchar(255),
	`relevantieTags` text,
	`toetsingskaderBeschrijving` text,
	`status` enum('concept','actief','inactief') DEFAULT 'actief',
	`bron` enum('ai_gegenereerd','handmatig','import') DEFAULT 'handmatig',
	`createdBy` int,
	`approvedBy` int,
	`approvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kennisbank_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kennisbank_rijks_wetgeving` (
	`id` int AUTO_INCREMENT NOT NULL,
	`wetNaam` varchar(255) NOT NULL,
	`wetAfkorting` varchar(50),
	`samenvatting` text NOT NULL,
	`toepassingscriteria` text NOT NULL,
	`relevanteActiviteiten` json,
	`bronUrl` text,
	`versie` varchar(50),
	`status` enum('actief','inactief') DEFAULT 'actief',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `kennisbank_rijks_wetgeving_id` PRIMARY KEY(`id`)
);
