export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  appUrl: process.env.APP_URL ?? "",
  dsoApiKey: process.env.DSO_API_KEY ?? "",
  togetherApiKey: process.env.TOGETHER_API_KEY ?? "",
  ruimtelijkeplannenApiKey: process.env.RUIMTELIJKEPLANNEN_API_KEY ?? "",
  bagApiKey: process.env.BAG_API_KEY ?? "",
  aeriusApiKey: process.env.AERIUS_API_KEY ?? "",
  groqApiKey: process.env.GROQ_API_KEY ?? "",
};
