/**
 * Omgevingsscan Indicator Catalog
 * 90+ indicators across 14 themes for spatial context analysis
 */

export interface IndicatorDefinition {
  code: string;
  theme: string;
  humanName: string;
  description: string;
  sourceType: 'WFS' | 'WMS' | 'REST' | 'DERIVED' | 'MANUAL';
  sourceUrl?: string;
  computeMethod: 'intersect' | 'distance' | 'attribute' | 'derived';
  bufferM: number;
  triggers: string[];
  mapLayerId?: string;
}

export const INDICATOR_THEMES = [
  { code: 'basis', label: 'Basisgegevens', color: '#1e40af' },
  { code: 'plan', label: 'Planologie', color: '#7c3aed' },
  { code: 'dso', label: 'DSO / Omgevingsloket', color: '#0891b2' },
  { code: 'natuur', label: 'Natuur & Ecologie', color: '#16a34a' },
  { code: 'landschap', label: 'Landschap', color: '#65a30d' },
  { code: 'water', label: 'Water & Waterkeringen', color: '#2563eb' },
  { code: 'bodem', label: 'Bodem & Ondergrond', color: '#92400e' },
  { code: 'milieu', label: 'Geluid & Milieu', color: '#dc2626' },
  { code: 'veiligheid', label: 'Externe Veiligheid', color: '#ea580c' },
  { code: 'erfgoed', label: 'Cultuurhistorie & Erfgoed', color: '#a16207' },
  { code: 'agrarisch', label: 'Agrarisch & Geur', color: '#4d7c0f' },
  { code: 'infra', label: 'Infrastructuur & Leidingen', color: '#6b7280' },
  { code: 'mobiliteit', label: 'Mobiliteit', color: '#475569' },
  { code: 'overig', label: 'Gezondheid & Overig', color: '#78716c' },
] as const;

export const INDICATOR_CATALOG: IndicatorDefinition[] = [
  // ===== BASIS (5) =====
  {
    code: 'BAG_PAND',
    theme: 'basis',
    humanName: 'BAG Pandgegevens',
    description: 'Bouwjaar, status, oppervlakte en gebruiksdoel uit de Basisregistratie Adressen en Gebouwen',
    sourceType: 'REST',
    sourceUrl: 'https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: ['bouw', 'verbouw', 'sloop', 'functiewijziging', 'uitbreid'],
  },
  {
    code: 'KADASTER_PERCEEL',
    theme: 'basis',
    humanName: 'Kadastraal perceel',
    description: 'Perceelgrenzen, oppervlakte en kadastrale aanduiding',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/kadaster/kadastralekaart/wfs/v5_0',
    computeMethod: 'intersect',
    bufferM: 10,
    triggers: ['bouw', 'nieuwbouw', 'splitsen', 'samenvoegen', 'erfgrens'],
    mapLayerId: 'kadaster',
  },
  {
    code: 'BGT_TOPOGRAFIE',
    theme: 'basis',
    humanName: 'BGT Topografie',
    description: 'Grootschalige topografie: verharding, groen, water en bebouwing',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/lv/bgt/wfs/v1_0',
    computeMethod: 'intersect',
    bufferM: 50,
    triggers: ['parkeer', 'verharding', 'groen', 'tuin', 'waterberging'],
    mapLayerId: 'bgt',
  },
  {
    code: 'BESTUURLIJK_GEBIED',
    theme: 'basis',
    humanName: 'Bestuurlijk gebied',
    description: 'Gemeente, provincie, waterschap en veiligheidsregio',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'LUCHTFOTO',
    theme: 'basis',
    humanName: 'Actuele luchtfoto',
    description: 'Meest recente luchtfoto van de locatie (PDOK)',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/hwh/luchtfotorgb/wmts/v1_0',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
    mapLayerId: 'luchtfoto',
  },

  // ===== PLAN (7) =====
  {
    code: 'BESTEMMINGSPLAN',
    theme: 'plan',
    humanName: 'Bestemmingsplan',
    description: 'Vigerende bestemmingsplannen op de locatie',
    sourceType: 'REST',
    sourceUrl: 'https://ruimte.omgevingswet.overheid.nl/ruimtelijke-plannen/api/opvragen/v4',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'verbouw', 'functiewijziging', 'afwijken'],
    mapLayerId: 'bestemmingsplan',
  },
  {
    code: 'BESTEMMING',
    theme: 'plan',
    humanName: 'Bestemmingsvlak',
    description: 'Enkelbestemming(en) op de locatie (wonen, bedrijf, etc.)',
    sourceType: 'REST',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'functiewijziging'],
  },
  {
    code: 'DUBBELBESTEMMING',
    theme: 'plan',
    humanName: 'Dubbelbestemming',
    description: 'Dubbelbestemmingen zoals Waarde-Archeologie, Waterstaat-Waterkering',
    sourceType: 'REST',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'graven', 'fundering'],
  },
  {
    code: 'GEBIEDSAANDUIDING',
    theme: 'plan',
    humanName: 'Gebiedsaanduiding',
    description: 'Gebiedsaanduidingen zoals geluidzone, veiligheidszone, milieuzone',
    sourceType: 'REST',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'milieu', 'geluid'],
  },
  {
    code: 'BOUWVLAK',
    theme: 'plan',
    humanName: 'Bouwvlak',
    description: 'Bouwvlak en maatvoering (max hoogte, max percentage, etc.)',
    sourceType: 'REST',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'uitbreid', 'aanbouw'],
  },
  {
    code: 'PLANREGELS',
    theme: 'plan',
    humanName: 'Planregels (letterlijk)',
    description: 'Letterlijke tekst van relevante planregels',
    sourceType: 'REST',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'OMGEVINGSPLAN',
    theme: 'plan',
    humanName: 'Omgevingsplan',
    description: 'Regels uit het gemeentelijk omgevingsplan (TAM/nieuw)',
    sourceType: 'REST',
    sourceUrl: 'https://service.omgevingswet.overheid.nl/publiek/omgevingsdocument/api/presenteren/v7',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'functiewijziging', 'milieu'],
  },

  // ===== DSO (5) =====
  {
    code: 'DSO_ACTIVITEITEN',
    theme: 'dso',
    humanName: 'DSO Activiteiten',
    description: 'Activiteiten uit de DSO-aanvraag (vergunningcheck)',
    sourceType: 'REST',
    sourceUrl: 'https://service.omgevingswet.overheid.nl/publiek/toepasbare-regels/api/rtrgegevens/v2',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'DSO_VERGUNNINGCHECK',
    theme: 'dso',
    humanName: 'DSO Vergunningcheck',
    description: 'Indicatieve uitkomst vergunningcheck (vergunningplichtig/meldingplichtig/vrij)',
    sourceType: 'REST',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'DSO_INDIENINGSVEREISTEN',
    theme: 'dso',
    humanName: 'Indieningsvereisten',
    description: 'Vereiste documenten en gegevens voor de aanvraag',
    sourceType: 'REST',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'DSO_BEVOEGD_GEZAG',
    theme: 'dso',
    humanName: 'Bevoegd gezag',
    description: 'Welke overheid bevoegd gezag is voor deze aanvraag',
    sourceType: 'REST',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },
  {
    code: 'DSO_MAATREGELEN',
    theme: 'dso',
    humanName: 'Maatregelen op maat',
    description: 'Specifieke maatregelen en voorschriften uit toepasbare regels',
    sourceType: 'REST',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: [],
  },

  // ===== NATUUR (10) =====
  {
    code: 'NATURA2000',
    theme: 'natuur',
    humanName: 'Natura 2000',
    description: 'Natura 2000 gebieden (Vogel- en Habitatrichtlijn)',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rvo/natura2000/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 10000,
    triggers: ['bouw', 'sloop', 'stikstof', 'natuur', 'dier'],
    mapLayerId: 'natura2000',
  },
  {
    code: 'NNN',
    theme: 'natuur',
    humanName: 'Natuurnetwerk Nederland (NNN)',
    description: 'Ecologische hoofdstructuur / Natuurnetwerk Nederland — pixel-based WMS detectie',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/provincies/nnn/wms/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'natuur', 'groen', 'kap', 'sloop', 'verbouw'],
    mapLayerId: 'nnn',
  },
  {
    code: 'NATIONAAL_PARK',
    theme: 'natuur',
    humanName: 'Nationaal Park',
    description: 'Nationale parken in Nederland',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rvo/beschermdegebieden/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 5000,
    triggers: ['bouw', 'natuur'],
    mapLayerId: 'nationaal_park',
  },
  {
    code: 'BESCHERMD_NATUURGEBIED',
    theme: 'natuur',
    humanName: 'Beschermd natuurgebied',
    description: 'Overige beschermde natuurgebieden (provinciaal/nationaal)',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rvo/beschermdegebieden/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 3000,
    triggers: ['bouw', 'natuur', 'groen'],
  },
  {
    code: 'STIKSTOF_AERIUS',
    theme: 'natuur',
    humanName: 'Stikstof (AERIUS)',
    description: 'Stikstofdepositie berekening via AERIUS Calculator',
    sourceType: 'REST',
    sourceUrl: 'https://connect.aerius.nl/api/',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'verkeer', 'industrie', 'veehouderij'],
  },
  {
    code: 'ECOLOGISCHE_VERBINDING',
    theme: 'natuur',
    humanName: 'Ecologische verbindingszone',
    description: 'Ecologische verbindingszones tussen natuurgebieden',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 1000,
    triggers: ['bouw', 'infra', 'weg'],
  },
  {
    code: 'WEIDEVOGELGEBIED',
    theme: 'natuur',
    humanName: 'Weidevogelgebied',
    description: 'Gebieden met belangrijke weidevogelpopulaties',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['bouw', 'agrarisch', 'windturbine'],
  },
  {
    code: 'FAUNAPASSAGE',
    theme: 'natuur',
    humanName: 'Faunapassage',
    description: 'Faunapassages en ecoducten',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['infra', 'weg', 'brug'],
  },
  {
    code: 'BOMENKAART',
    theme: 'natuur',
    humanName: 'Bomenkaart / Kapvergunning',
    description: 'Beschermde bomen en kapvergunningplicht',
    sourceType: 'MANUAL',
    computeMethod: 'intersect',
    bufferM: 25,
    triggers: ['kap', 'boom', 'groen', 'tuin'],
  },
  {
    code: 'SOORTENBESCHERMING',
    theme: 'natuur',
    humanName: 'Soortenbescherming',
    description: 'Beschermde dier- en plantensoorten (quickscan flora/fauna)',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['sloop', 'verbouw', 'kap', 'renovatie'],
  },

  // ===== LANDSCHAP (5) =====
  {
    code: 'LANDSCHAPSTYPE',
    theme: 'landschap',
    humanName: 'Landschapstype',
    description: 'Type landschap (polder, strandwal, veenweide, etc.)',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw'],
  },
  {
    code: 'AARDKUNDIG_WAARDEVOL',
    theme: 'landschap',
    humanName: 'Aardkundig waardevol gebied',
    description: 'Gebieden met bijzondere aardkundige waarden',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 500,
    triggers: ['graven', 'ontgrond'],
  },
  {
    code: 'STILTEGEBIED',
    theme: 'landschap',
    humanName: 'Stiltegebied',
    description: 'Provinciale stiltegebieden — via PDOK WMS GetFeatureInfo',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/provincies/stiltegebieden/wms/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['industrie', 'horeca', 'evenement', 'bouw', 'geluid'],
    mapLayerId: 'stiltegebied',
  },
  {
    code: 'DONKERTEGEBIED',
    theme: 'landschap',
    humanName: 'Donkertegebied',
    description: 'Gebieden met bijzondere duisternis (lichthinder)',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['verlichting', 'kas', 'sport'],
  },
  {
    code: 'WERELDERFGOED',
    theme: 'landschap',
    humanName: 'UNESCO Werelderfgoed',
    description: 'UNESCO Werelderfgoed locaties en bufferzones',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 2000,
    triggers: ['bouw', 'nieuwbouw', 'sloop'],
  },

  // ===== WATER (11) =====
  {
    code: 'WATERKERING',
    theme: 'water',
    humanName: 'Waterkering',
    description: 'Primaire en regionale waterkeringen (dijken, dammen)',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rws/legger/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['bouw', 'graven', 'fundering'],
    mapLayerId: 'waterkering',
  },
  {
    code: 'BESCHERMINGSZONE_WATERKERING',
    theme: 'water',
    humanName: 'Beschermingszone waterkering',
    description: 'Beschermingszones rondom waterkeringen',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'graven'],
    mapLayerId: 'beschermingszone_waterkering',
  },
  {
    code: 'WATERGANG',
    theme: 'water',
    humanName: 'Watergang',
    description: 'Watergangen en sloten (legger waterschap)',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 100,
    triggers: ['bouw', 'lozen', 'dempen'],
  },
  {
    code: 'OVERSTROMINGSRISICO',
    theme: 'water',
    humanName: 'Overstromingsrisico',
    description: 'Overstromingsrisicogebieden (Risicokaart)',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/rws/overstromingsrisico/wms/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'kelder'],
    mapLayerId: 'overstromingsrisico',
  },
  {
    code: 'GRONDWATERBESCHERMING',
    theme: 'water',
    humanName: 'Grondwaterbeschermingsgebied',
    description: 'Waterwingebieden, grondwaterbeschermingsgebieden en boringsvrije zones',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/provincies/grondwaterbeschermingsgebieden/wfs/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bodem', 'grondwater', 'opslag', 'tank'],
    mapLayerId: 'grondwaterbescherming',
  },
  {
    code: 'WATERWINGEBIED',
    theme: 'water',
    humanName: 'Waterwingebied',
    description: 'Actieve waterwingebieden voor drinkwaterproductie',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bodem', 'grondwater', 'boring'],
  },
  {
    code: 'KEUR_WATERSCHAP',
    theme: 'water',
    humanName: 'Keur waterschap',
    description: 'Vergunningplicht en meldingsplicht op grond van de Keur',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['lozen', 'dempen', 'graven', 'bouw'],
  },
  {
    code: 'RIOLERINGSGEBIED',
    theme: 'water',
    humanName: 'Rioleringsgebied',
    description: 'Type rioolstelsel (gemengd, gescheiden, DWA/HWA)',
    sourceType: 'MANUAL',
    computeMethod: 'attribute',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'lozen'],
  },
  {
    code: 'WATERTOETS',
    theme: 'water',
    humanName: 'Watertoets vereist',
    description: 'Indicatie of watertoets/wateradvies nodig is',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'verharding'],
  },
  {
    code: 'ZWEMWATER',
    theme: 'water',
    humanName: 'Zwemwater',
    description: 'Officiële zwemwaterlocaties en kwaliteit',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['lozen', 'recreatie'],
  },
  {
    code: 'NATTE_NATUUR',
    theme: 'water',
    humanName: 'Natte natuur / Wetlands',
    description: 'Natte natuurgebieden en Ramsar-wetlands',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 1000,
    triggers: ['lozen', 'grondwater', 'natuur'],
  },

  // ===== BODEM (6) =====
  {
    code: 'BODEMKWALITEIT',
    theme: 'bodem',
    humanName: 'Bodemkwaliteit',
    description: 'Bekende bodemverontreinigingen en saneringslocaties',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/rivm/bodemkwaliteit/wms/v1_0',
    computeMethod: 'intersect',
    bufferM: 50,
    triggers: ['bouw', 'graven', 'fundering', 'bodem'],
    mapLayerId: 'bodemkwaliteit',
  },
  {
    code: 'BODEMFUNCTIEKAART',
    theme: 'bodem',
    humanName: 'Bodemfunctiekaart',
    description: 'Bodemfunctieklasse (wonen, industrie, landbouw)',
    sourceType: 'WMS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['functiewijziging', 'grondverzet'],
  },
  {
    code: 'ONTPLOFBARE_OORLOGSRESTEN',
    theme: 'bodem',
    humanName: 'Ontplofbare oorlogsresten (OO)',
    description: 'Verdacht gebied voor niet-gesprongen explosieven',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['graven', 'fundering', 'bouw'],
  },
  {
    code: 'ONDERGRONDSE_TANKS',
    theme: 'bodem',
    humanName: 'Ondergrondse tanks',
    description: 'Bekende ondergrondse opslagtanks (BRO)',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 25,
    triggers: ['graven', 'sloop', 'tank'],
  },
  {
    code: 'FUNDERINGSPROBLEMATIEK',
    theme: 'bodem',
    humanName: 'Funderingsproblematiek',
    description: 'Gebieden met bekende funderingsproblemen (houten palen, zetting)',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['verbouw', 'fundering', 'uitbreid'],
  },
  {
    code: 'ASBEST_RISICO',
    theme: 'bodem',
    humanName: 'Asbestrisico',
    description: 'Indicatie asbestrisico op basis van bouwjaar (<1994)',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['sloop', 'verbouw', 'renovatie', 'dak'],
  },

  // ===== MILIEU (7) =====
  {
    code: 'GELUIDZONE_WEG',
    theme: 'milieu',
    humanName: 'Geluidzone weg',
    description: 'Geluidzones langs wegen (Wet geluidhinder)',
    sourceType: 'WMS',
    sourceUrl: 'https://service.pdok.nl/rivm/geluid/wms/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'geluidgevoelig'],
    mapLayerId: 'geluidzone_weg',
  },
  {
    code: 'GELUIDZONE_SPOOR',
    theme: 'milieu',
    humanName: 'Geluidzone spoor',
    description: 'Geluidzones langs spoorwegen',
    sourceType: 'WMS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'geluidgevoelig'],
    mapLayerId: 'geluidzone_spoor',
  },
  {
    code: 'GELUIDZONE_INDUSTRIE',
    theme: 'milieu',
    humanName: 'Geluidzone industrie',
    description: 'Geluidzones rondom industrieterreinen',
    sourceType: 'WMS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'geluidgevoelig'],
    mapLayerId: 'geluidzone_industrie',
  },
  {
    code: 'GELUIDZONE_LUCHTVAART',
    theme: 'milieu',
    humanName: 'Geluidzone luchtvaart',
    description: 'Geluidzones rondom luchthavens en vliegvelden',
    sourceType: 'WMS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen'],
  },
  {
    code: 'LUCHTKWALITEIT',
    theme: 'milieu',
    humanName: 'Luchtkwaliteit (NSL)',
    description: 'Concentraties fijnstof en NO2 (Nationaal Samenwerkingsprogramma Luchtkwaliteit)',
    sourceType: 'WMS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'verkeer'],
  },
  {
    code: 'GEURZONE',
    theme: 'milieu',
    humanName: 'Geurzone',
    description: 'Geurcontouren van veehouderijen en industrie',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['wonen', 'bouw', 'veehouderij'],
    mapLayerId: 'geurcontouren',
  },
  {
    code: 'TRILLINGEN',
    theme: 'milieu',
    humanName: 'Trillingsgevoelig',
    description: 'Trillingszones langs spoor en industrie',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['wonen', 'bouw', 'spoor'],
  },

  // ===== EXTERNE VEILIGHEID (5) =====
  {
    code: 'BEVI_INRICHTING',
    theme: 'veiligheid',
    humanName: 'Bevi-inrichting',
    description: 'Risicovolle inrichtingen (Besluit externe veiligheid inrichtingen)',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rivm/rev/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 1500,
    triggers: ['bouw', 'wonen', 'kwetsbaar'],
    mapLayerId: 'bevi',
  },
  {
    code: 'BUISLEIDING',
    theme: 'veiligheid',
    humanName: 'Buisleiding (gevaarlijke stoffen)',
    description: 'Buisleidingen met gevaarlijke stoffen (Bevb)',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['bouw', 'graven'],
    mapLayerId: 'buisleidingen',
  },
  {
    code: 'RISICOCONTOUR',
    theme: 'veiligheid',
    humanName: 'Risicocontour (PR/GR)',
    description: 'Plaatsgebonden risico en groepsrisico contouren',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'kwetsbaar'],
  },
  {
    code: 'LPG_TANKSTATION',
    theme: 'veiligheid',
    humanName: 'LPG-tankstation',
    description: 'LPG-tankstations en veiligheidszones',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 150,
    triggers: ['bouw', 'wonen'],
  },
  {
    code: 'VUURWERK_OPSLAG',
    theme: 'veiligheid',
    humanName: 'Vuurwerkopslag',
    description: 'Vuurwerkopslagplaatsen en veiligheidsafstanden',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 800,
    triggers: ['bouw', 'wonen'],
  },

  // ===== ERFGOED (7) =====
  {
    code: 'RIJKSMONUMENT',
    theme: 'erfgoed',
    humanName: 'Rijksmonument',
    description: 'Rijksmonumenten (Rijksdienst voor het Cultureel Erfgoed)',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rce/rijksmonumenten/wfs/v1_0',
    computeMethod: 'distance',
    bufferM: 100,
    triggers: ['bouw', 'verbouw', 'sloop', 'monument'],
    mapLayerId: 'rijksmonumenten',
  },
  {
    code: 'GEMEENTELIJK_MONUMENT',
    theme: 'erfgoed',
    humanName: 'Gemeentelijk monument',
    description: 'Gemeentelijke monumenten en beeldbepalende panden',
    sourceType: 'MANUAL',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'verbouw', 'sloop'],
  },
  {
    code: 'BESCHERMD_GEZICHT',
    theme: 'erfgoed',
    humanName: 'Beschermd stads-/dorpsgezicht',
    description: 'Beschermde stads- en dorpsgezichten',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rce/beschermdestadsdorpsgezichten/wfs/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'verbouw', 'sloop', 'reclame'],
    mapLayerId: 'beschermd_gezicht',
  },
  {
    code: 'ARCHEOLOGIE',
    theme: 'erfgoed',
    humanName: 'Archeologische verwachtingswaarde',
    description: 'Archeologische verwachtingskaart en dubbelbestemming Waarde-Archeologie',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['graven', 'fundering', 'bouw', 'nieuwbouw'],
    mapLayerId: 'archeologie',
  },
  {
    code: 'CULTUURLANDSCHAP',
    theme: 'erfgoed',
    humanName: 'Cultuurhistorisch landschap',
    description: 'Gebieden met bijzondere cultuurhistorische waarden',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'nieuwbouw', 'landschap'],
  },
  {
    code: 'HISTORISCHE_BUITENPLAATS',
    theme: 'erfgoed',
    humanName: 'Historische buitenplaats',
    description: 'Historische buitenplaatsen en landgoederen',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['bouw', 'kap'],
  },
  {
    code: 'VERDRAG_MALTA',
    theme: 'erfgoed',
    humanName: 'Verdrag van Malta',
    description: 'Archeologisch onderzoek vereist bij bodemingreep (vrijstellingsgrenzen)',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['graven', 'fundering', 'bouw'],
  },

  // ===== AGRARISCH (7) =====
  {
    code: 'GEWASPERCEEL',
    theme: 'agrarisch',
    humanName: 'Gewasperceel (BRP)',
    description: 'Basisregistratie Gewaspercelen - actueel gewastype',
    sourceType: 'WFS',
    sourceUrl: 'https://service.pdok.nl/rvo/brpgewaspercelen/wfs/v1_0',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['agrarisch', 'landbouw', 'grond'],
    mapLayerId: 'gewaspercelen',
  },
  {
    code: 'GEURCONTOUR_VEEHOUDERIJ',
    theme: 'agrarisch',
    humanName: 'Geurcontour veehouderij',
    description: 'Geurcontouren rondom veehouderijen (Wet geurhinder)',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['wonen', 'bouw', 'veehouderij'],
    mapLayerId: 'geurcontouren',
  },
  {
    code: 'GLASTUINBOUW',
    theme: 'agrarisch',
    humanName: 'Glastuinbouwgebied',
    description: 'Concentratiegebieden glastuinbouw',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['kas', 'glastuinbouw', 'agrarisch'],
  },
  {
    code: 'LANDBOUWGROND',
    theme: 'agrarisch',
    humanName: 'Landbouwgrond',
    description: 'Agrarische gronden en bestemmingen',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['agrarisch', 'landbouw', 'functiewijziging'],
  },
  {
    code: 'MESTVERWERKING',
    theme: 'agrarisch',
    humanName: 'Mestverwerkingslocatie',
    description: 'Mestverwerkingsinstallaties en afstandsnormen',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['wonen', 'bouw'],
  },
  {
    code: 'SPUITZONE',
    theme: 'agrarisch',
    humanName: 'Spuitzone',
    description: 'Spuitzones rondom agrarische percelen (gewasbescherming)',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 50,
    triggers: ['wonen', 'bouw', 'agrarisch'],
  },
  {
    code: 'DIERENWELZIJN',
    theme: 'agrarisch',
    humanName: 'Dierenwelzijnszone',
    description: 'Zones met restricties voor dierhouderij',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['veehouderij', 'dier'],
  },

  // ===== INFRA (6) =====
  {
    code: 'HOOGSPANNING',
    theme: 'infra',
    humanName: 'Hoogspanningsleiding',
    description: 'Hoogspanningsleidingen en magneetveldzone',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['bouw', 'wonen'],
    mapLayerId: 'hoogspanning',
  },
  {
    code: 'GASLEIDING',
    theme: 'infra',
    humanName: 'Gasleiding (hogedruk)',
    description: 'Hogedruk gasleidingen en veiligheidsstroken',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['bouw', 'graven'],
    mapLayerId: 'gasleidingen',
  },
  {
    code: 'KLIC_MELDING',
    theme: 'infra',
    humanName: 'KLIC-melding vereist',
    description: 'Kabels en leidingen - KLIC-melding verplicht bij graven >20cm',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['graven', 'fundering', 'bouw'],
  },
  {
    code: 'SPOORWEG',
    theme: 'infra',
    humanName: 'Spoorweg',
    description: 'Spoorlijnen en veiligheidszones',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['bouw', 'wonen'],
  },
  {
    code: 'RIJKSWEG',
    theme: 'infra',
    humanName: 'Rijksweg',
    description: 'Rijkswegen en geluidzones',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 600,
    triggers: ['bouw', 'wonen'],
  },
  {
    code: 'VAARWEG',
    theme: 'infra',
    humanName: 'Vaarweg',
    description: 'Vaarwegen en oeverbeschermingszones',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 100,
    triggers: ['bouw', 'lozen', 'steiger'],
  },

  // ===== MOBILITEIT (3) =====
  {
    code: 'PARKEERDRUK',
    theme: 'mobiliteit',
    humanName: 'Parkeerdruk',
    description: 'Parkeernormen en parkeerdruk in het gebied',
    sourceType: 'DERIVED',
    computeMethod: 'derived',
    bufferM: 0,
    triggers: ['bouw', 'wonen', 'horeca', 'winkel'],
  },
  {
    code: 'OV_BEREIKBAARHEID',
    theme: 'mobiliteit',
    humanName: 'OV-bereikbaarheid',
    description: 'Nabijheid van OV-haltes en stations',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 1000,
    triggers: ['bouw', 'wonen', 'kantoor'],
  },
  {
    code: 'FIETSROUTE',
    theme: 'mobiliteit',
    humanName: 'Fietsroute',
    description: 'Hoofdfietsroutes en fietssnelwegen',
    sourceType: 'WFS',
    computeMethod: 'distance',
    bufferM: 200,
    triggers: ['infra', 'weg'],
  },

  // ===== GEZONDHEID & OVERIG (4) =====
  {
    code: 'ZORGINSTELLING',
    theme: 'overig',
    humanName: 'Zorginstelling nabijheid',
    description: 'Nabijheid van ziekenhuizen, verpleeghuizen en zorginstellingen',
    sourceType: 'DERIVED',
    computeMethod: 'distance',
    bufferM: 500,
    triggers: ['bouw', 'wonen', 'zorg'],
  },
  {
    code: 'SCHOOL_KINDEROPVANG',
    theme: 'overig',
    humanName: 'School / Kinderopvang',
    description: 'Nabijheid van scholen en kinderopvang (kwetsbare objecten)',
    sourceType: 'DERIVED',
    computeMethod: 'distance',
    bufferM: 300,
    triggers: ['industrie', 'veiligheid', 'horeca'],
  },
  {
    code: 'LUCHTVAART_BEPERKING',
    theme: 'overig',
    humanName: 'Luchtvaartbeperking',
    description: 'Luchtvaartbeperkingen en hoogterestricties',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'hoogte', 'windturbine'],
    mapLayerId: 'luchtvaart_beperkingen',
  },
  {
    code: 'DEFENSIE_ZONE',
    theme: 'overig',
    humanName: 'Defensiezone',
    description: 'Militaire zones en beperkingsgebieden',
    sourceType: 'WFS',
    computeMethod: 'intersect',
    bufferM: 0,
    triggers: ['bouw', 'hoogte'],
    mapLayerId: 'defensie_zones',
  },
];

export function getIndicatorsByTheme(theme: string): IndicatorDefinition[] {
  return INDICATOR_CATALOG.filter(i => i.theme === theme);
}

export function getIndicatorByCode(code: string): IndicatorDefinition | undefined {
  return INDICATOR_CATALOG.find(i => i.code === code);
}

export function getAllThemes(): typeof INDICATOR_THEMES {
  return INDICATOR_THEMES;
}
